//lint:file-ignore U1000,ST1012 generated file
// AUTOGENERATED BY storj.io/dbx
// DO NOT EDIT.

package dbx

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"

	"github.com/jackc/pgx/v5/pgconn"
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Prevent conditional imports from causing build failures.
var _ = strconv.Itoa
var _ = strings.LastIndex
var _ = fmt.Sprint
var _ sync.Mutex

var (
	WrapErr     = func(err *Error) error { return err }
	Logger      func(format string, args ...any)
	ShouldRetry func(driver string, err error) bool

	errTooManyRows       = errors.New("too many rows")
	errUnsupportedDriver = errors.New("unsupported driver")
	errEmptyUpdate       = errors.New("empty update")
)

func logError(format string, args ...any) {
	if Logger != nil {
		Logger(format, args...)
	}
}

type ErrorCode int

const (
	ErrorCode_Unknown ErrorCode = iota
	ErrorCode_UnsupportedDriver
	ErrorCode_NoRows
	ErrorCode_TxDone
	ErrorCode_TooManyRows
	ErrorCode_ConstraintViolation
	ErrorCode_EmptyUpdate
)

type Error struct {
	Err         error
	Code        ErrorCode
	Driver      string
	Constraint  string
	QuerySuffix string
}

func (e *Error) Error() string {
	return e.Err.Error()
}

func (e *Error) Unwrap() error {
	return e.Err
}

func wrapErr(e *Error) error {
	if WrapErr == nil {
		return e
	}
	return WrapErr(e)
}

func makeErr(err error) error {
	if err == nil {
		return nil
	}
	var e *Error
	if errors.As(err, &e) {
		return wrapErr(e)
	}
	e = &Error{Err: err}
	switch {
	case errors.Is(err, sql.ErrNoRows):
		e.Code = ErrorCode_NoRows
	case errors.Is(err, sql.ErrTxDone):
		e.Code = ErrorCode_TxDone
	}
	return wrapErr(e)
}

func shouldRetry(driver string, err error) bool {
	if ShouldRetry == nil {
		return false
	}
	return ShouldRetry(driver, err)
}

func unsupportedDriver(driver string) error {
	return wrapErr(&Error{
		Err:    errUnsupportedDriver,
		Code:   ErrorCode_UnsupportedDriver,
		Driver: driver,
	})
}

func emptyUpdate() error {
	return wrapErr(&Error{
		Err:  errEmptyUpdate,
		Code: ErrorCode_EmptyUpdate,
	})
}

func tooManyRows(query_suffix string) error {
	return wrapErr(&Error{
		Err:         errTooManyRows,
		Code:        ErrorCode_TooManyRows,
		QuerySuffix: query_suffix,
	})
}

func constraintViolation(err error, constraint string) error {
	return wrapErr(&Error{
		Err:        err,
		Code:       ErrorCode_ConstraintViolation,
		Constraint: constraint,
	})
}

func closeRows(rows *sql.Rows, err *error) {
	rowsErr := rows.Err()
	closeErr := rows.Close()
	if *err != nil {
		// throw away errors from .Err() and .Close(), if any; they are almost certainly less important
		// than the error we already have
		return
	}
	if rowsErr != nil {
		// throw away error from .Close(), if any; it is probably less important
		*err = rowsErr
		return
	}
	*err = closeErr
}

type driver interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

type DB struct {
	*sql.DB
	dbMethods

	Hooks struct {
		Now func() time.Time
	}

	driver string
}

func Open(driver, source string) (db *DB, err error) {
	var sql_db *sql.DB
	switch driver {
	case "pgx":
		sql_db, err = openpgx(source)
	default:
		return nil, unsupportedDriver(driver)
	}
	if err != nil {
		return nil, makeErr(err)
	}
	defer func(sql_db *sql.DB) {
		if err != nil {
			_ = sql_db.Close()
		}
	}(sql_db)

	if err := sql_db.Ping(); err != nil {
		return nil, makeErr(err)
	}

	db = &DB{
		DB: sql_db,

		driver: driver,
	}
	db.Hooks.Now = time.Now

	switch driver {
	case "pgx":
		db.dbMethods = newpgx(db)
	default:
		return nil, unsupportedDriver(driver)
	}

	return db, nil
}

func (obj *DB) Close() (err error) {
	return obj.makeErr(obj.DB.Close())
}

func (obj *DB) Open(ctx context.Context) (*Tx, error) {
	tx, err := obj.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, obj.makeErr(err)
	}

	return &Tx{
		Tx:        tx,
		txMethods: obj.wrapTx(tx),
	}, nil
}

func DeleteAll(ctx context.Context, db *DB) (int64, error) {
	tx, err := db.Open(ctx)
	if err != nil {
		return 0, err
	}
	defer func() {
		if err == nil {
			err = db.makeErr(tx.Commit())
			return
		}

		if err_rollback := tx.Rollback(); err_rollback != nil {
			logError("delete-all: rollback failed: %v", db.makeErr(err_rollback))
		}
	}()
	return tx.deleteAll(ctx)
}

type Tx struct {
	Tx *sql.Tx
	txMethods
}

func (tx *Tx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	return tx.Tx.ExecContext(ctx, query, args...)
}
func (tx *Tx) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	return tx.Tx.QueryContext(ctx, query, args...)
}
func (tx *Tx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	return tx.Tx.QueryRowContext(ctx, query, args...)
}

type dialectTx struct {
	tx *sql.Tx
}

func (tx *dialectTx) Commit() (err error) {
	return makeErr(tx.tx.Commit())
}

func (tx *dialectTx) Rollback() (err error) {
	return makeErr(tx.tx.Rollback())
}

type pgxImpl struct {
	db      *DB
	dialect __sqlbundle_pgx
	driver  driver
	txn     bool
}

func (obj *pgxImpl) Rebind(s string) string {
	return obj.dialect.Rebind(s)
}

func (obj *pgxImpl) logStmt(stmt string, args ...any) {
	pgxLogStmt(stmt, args...)
}

func (obj *pgxImpl) makeErr(err error) error {
	constraint, ok := obj.isConstraintError(err)
	if ok {
		return constraintViolation(err, constraint)
	}
	return makeErr(err)
}

func (obj *pgxImpl) shouldRetry(err error) bool {
	return !obj.txn && shouldRetry(obj.db.driver, err)
}

type pgxImpl_retryingRow struct {
	obj   *pgxImpl
	ctx   context.Context
	query string
	args  []any
}

func (obj *pgxImpl) queryRowContext(ctx context.Context, query string, args ...any) *pgxImpl_retryingRow {
	return &pgxImpl_retryingRow{
		obj:   obj,
		ctx:   ctx,
		query: query,
		args:  args,
	}
}

func (rows *pgxImpl_retryingRow) Scan(dest ...any) error {
	for {
		err := rows.obj.driver.QueryRowContext(rows.ctx, rows.query, rows.args...).Scan(dest...)
		if err != nil {
			if rows.obj.shouldRetry(err) {
				continue
			}
			// caller will wrap this error
			return err
		}
		return nil
	}
}

type pgxDB struct {
	db *DB
	*pgxImpl
}

func newpgx(db *DB) *pgxDB {
	return &pgxDB{
		db: db,
		pgxImpl: &pgxImpl{
			db:     db,
			driver: db.DB,
		},
	}
}

func (obj *pgxDB) Schema() []string {
	return []string{

		`CREATE TABLE records (
	encryption_key_hash bytea NOT NULL,
	created_at timestamp with time zone NOT NULL,
	public boolean NOT NULL,
	public_project_id bytea,
	satellite_address text NOT NULL,
	macaroon_head bytea NOT NULL,
	expires_at timestamp with time zone,
	encrypted_secret_key bytea NOT NULL,
	encrypted_access_grant bytea NOT NULL,
	invalidation_reason text,
	invalidated_at timestamp with time zone,
	usage_tags text,
	project_created_at timestamp with time zone,
	PRIMARY KEY ( encryption_key_hash )
)`,
	}
}

func (obj *pgxDB) DropSchema() []string {
	return []string{

		`DROP TABLE IF EXISTS records`,
	}
}

func (obj *pgxDB) wrapTx(tx *sql.Tx) txMethods {
	return &pgxTx{
		dialectTx: dialectTx{tx: tx},
		pgxImpl: &pgxImpl{
			db:     obj.db,
			driver: tx,
			txn:    true,
		},
	}
}

type pgxTx struct {
	dialectTx
	*pgxImpl
}

func pgxLogStmt(stmt string, args ...any) {
	// TODO: render placeholders
	if Logger != nil {
		out := fmt.Sprintf("stmt: %s\nargs: %v\n", stmt, pretty(args))
		Logger(out)
	}
}

type pretty []any

func (p pretty) Format(f fmt.State, c rune) {
	_, _ = fmt.Fprint(f, "[")
nextval:
	for i, val := range p {
		if i > 0 {
			_, _ = fmt.Fprint(f, ", ")
		}
		rv := reflect.ValueOf(val)
		if rv.Kind() == reflect.Ptr {
			if rv.IsNil() {
				_, _ = fmt.Fprint(f, "NULL")
				continue
			}
			val = rv.Elem().Interface()
		}
		switch v := val.(type) {
		case string:
			_, _ = fmt.Fprintf(f, "%q", v)
		case time.Time:
			_, _ = fmt.Fprintf(f, "%s", v.Format(time.RFC3339Nano))
		case []byte:
			for _, b := range v {
				if !unicode.IsPrint(rune(b)) {
					_, _ = fmt.Fprintf(f, "%#x", v)
					continue nextval
				}
			}
			_, _ = fmt.Fprintf(f, "%q", v)
		default:
			_, _ = fmt.Fprintf(f, "%v", v)
		}
	}
	_, _ = fmt.Fprint(f, "]")
}

type Record struct {
	EncryptionKeyHash    []byte
	CreatedAt            time.Time
	Public               bool
	PublicProjectId      []byte
	SatelliteAddress     string
	MacaroonHead         []byte
	ExpiresAt            *time.Time
	EncryptedSecretKey   []byte
	EncryptedAccessGrant []byte
	InvalidationReason   *string
	InvalidatedAt        *time.Time
	UsageTags            *string
	ProjectCreatedAt     *time.Time
}

func (Record) _Table() string { return "records" }

type Record_Create_Fields struct {
	PublicProjectId    Record_PublicProjectId_Field
	ExpiresAt          Record_ExpiresAt_Field
	InvalidationReason Record_InvalidationReason_Field
	InvalidatedAt      Record_InvalidatedAt_Field
	UsageTags          Record_UsageTags_Field
	ProjectCreatedAt   Record_ProjectCreatedAt_Field
}

type Record_Update_Fields struct {
	InvalidationReason Record_InvalidationReason_Field
	InvalidatedAt      Record_InvalidatedAt_Field
}

type Record_EncryptionKeyHash_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func Record_EncryptionKeyHash(v []byte) Record_EncryptionKeyHash_Field {
	return Record_EncryptionKeyHash_Field{_set: true, _value: v}
}

func (f Record_EncryptionKeyHash_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_CreatedAt_Field struct {
	_set   bool
	_null  bool
	_value time.Time
}

func Record_CreatedAt(v time.Time) Record_CreatedAt_Field {
	return Record_CreatedAt_Field{_set: true, _value: v}
}

func (f Record_CreatedAt_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_Public_Field struct {
	_set   bool
	_null  bool
	_value bool
}

func Record_Public(v bool) Record_Public_Field {
	return Record_Public_Field{_set: true, _value: v}
}

func (f Record_Public_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_PublicProjectId_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func Record_PublicProjectId(v []byte) Record_PublicProjectId_Field {
	return Record_PublicProjectId_Field{_set: true, _value: v}
}

func Record_PublicProjectId_Raw(v []byte) Record_PublicProjectId_Field {
	if v == nil {
		return Record_PublicProjectId_Null()
	}
	return Record_PublicProjectId(v)
}

func Record_PublicProjectId_Null() Record_PublicProjectId_Field {
	return Record_PublicProjectId_Field{_set: true, _null: true}
}

func (f Record_PublicProjectId_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Record_PublicProjectId_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_SatelliteAddress_Field struct {
	_set   bool
	_null  bool
	_value string
}

func Record_SatelliteAddress(v string) Record_SatelliteAddress_Field {
	return Record_SatelliteAddress_Field{_set: true, _value: v}
}

func (f Record_SatelliteAddress_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_MacaroonHead_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func Record_MacaroonHead(v []byte) Record_MacaroonHead_Field {
	return Record_MacaroonHead_Field{_set: true, _value: v}
}

func (f Record_MacaroonHead_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_ExpiresAt_Field struct {
	_set   bool
	_null  bool
	_value *time.Time
}

func Record_ExpiresAt(v time.Time) Record_ExpiresAt_Field {
	return Record_ExpiresAt_Field{_set: true, _value: &v}
}

func Record_ExpiresAt_Raw(v *time.Time) Record_ExpiresAt_Field {
	if v == nil {
		return Record_ExpiresAt_Null()
	}
	return Record_ExpiresAt(*v)
}

func Record_ExpiresAt_Null() Record_ExpiresAt_Field {
	return Record_ExpiresAt_Field{_set: true, _null: true}
}

func (f Record_ExpiresAt_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Record_ExpiresAt_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_EncryptedSecretKey_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func Record_EncryptedSecretKey(v []byte) Record_EncryptedSecretKey_Field {
	return Record_EncryptedSecretKey_Field{_set: true, _value: v}
}

func (f Record_EncryptedSecretKey_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_EncryptedAccessGrant_Field struct {
	_set   bool
	_null  bool
	_value []byte
}

func Record_EncryptedAccessGrant(v []byte) Record_EncryptedAccessGrant_Field {
	return Record_EncryptedAccessGrant_Field{_set: true, _value: v}
}

func (f Record_EncryptedAccessGrant_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_InvalidationReason_Field struct {
	_set   bool
	_null  bool
	_value *string
}

func Record_InvalidationReason(v string) Record_InvalidationReason_Field {
	return Record_InvalidationReason_Field{_set: true, _value: &v}
}

func Record_InvalidationReason_Raw(v *string) Record_InvalidationReason_Field {
	if v == nil {
		return Record_InvalidationReason_Null()
	}
	return Record_InvalidationReason(*v)
}

func Record_InvalidationReason_Null() Record_InvalidationReason_Field {
	return Record_InvalidationReason_Field{_set: true, _null: true}
}

func (f Record_InvalidationReason_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Record_InvalidationReason_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_InvalidatedAt_Field struct {
	_set   bool
	_null  bool
	_value *time.Time
}

func Record_InvalidatedAt(v time.Time) Record_InvalidatedAt_Field {
	return Record_InvalidatedAt_Field{_set: true, _value: &v}
}

func Record_InvalidatedAt_Raw(v *time.Time) Record_InvalidatedAt_Field {
	if v == nil {
		return Record_InvalidatedAt_Null()
	}
	return Record_InvalidatedAt(*v)
}

func Record_InvalidatedAt_Null() Record_InvalidatedAt_Field {
	return Record_InvalidatedAt_Field{_set: true, _null: true}
}

func (f Record_InvalidatedAt_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Record_InvalidatedAt_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_UsageTags_Field struct {
	_set   bool
	_null  bool
	_value *string
}

func Record_UsageTags(v string) Record_UsageTags_Field {
	return Record_UsageTags_Field{_set: true, _value: &v}
}

func Record_UsageTags_Raw(v *string) Record_UsageTags_Field {
	if v == nil {
		return Record_UsageTags_Null()
	}
	return Record_UsageTags(*v)
}

func Record_UsageTags_Null() Record_UsageTags_Field {
	return Record_UsageTags_Field{_set: true, _null: true}
}

func (f Record_UsageTags_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Record_UsageTags_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

type Record_ProjectCreatedAt_Field struct {
	_set   bool
	_null  bool
	_value *time.Time
}

func Record_ProjectCreatedAt(v time.Time) Record_ProjectCreatedAt_Field {
	return Record_ProjectCreatedAt_Field{_set: true, _value: &v}
}

func Record_ProjectCreatedAt_Raw(v *time.Time) Record_ProjectCreatedAt_Field {
	if v == nil {
		return Record_ProjectCreatedAt_Null()
	}
	return Record_ProjectCreatedAt(*v)
}

func Record_ProjectCreatedAt_Null() Record_ProjectCreatedAt_Field {
	return Record_ProjectCreatedAt_Field{_set: true, _null: true}
}

func (f Record_ProjectCreatedAt_Field) isnull() bool { return !f._set || f._null || f._value == nil }

func (f Record_ProjectCreatedAt_Field) value() any {
	if !f._set || f._null {
		return nil
	}
	return f._value
}

func toUTC(t time.Time) time.Time {
	return t.UTC()
}

func toDate(t time.Time) time.Time {
	// keep up the minute portion so that translations between timezones will
	// continue to reflect properly.
	return t.Truncate(time.Minute)
}

//
// runtime support for building sql statements
//

type __sqlbundle_SQL interface {
	Render() string

	private()
}

type __sqlbundle_Dialect interface {
	// Rebind gives the opportunity to rewrite provided SQL into a SQL dialect.
	Rebind(sql string) string
}

type __sqlbundle_RenderOp int

const (
	__sqlbundle_NoFlatten __sqlbundle_RenderOp = iota
	__sqlbundle_NoTerminate
)

func __sqlbundle_RenderAll(dialect __sqlbundle_Dialect, sqls []__sqlbundle_SQL, ops ...__sqlbundle_RenderOp) []string {
	var rs []string
	for _, sql := range sqls {
		rs = append(rs, __sqlbundle_Render(dialect, sql, ops...))
	}
	return rs
}

func __sqlbundle_Render(dialect __sqlbundle_Dialect, sql __sqlbundle_SQL, ops ...__sqlbundle_RenderOp) string {
	out := sql.Render()

	flatten := true
	terminate := true
	for _, op := range ops {
		switch op {
		case __sqlbundle_NoFlatten:
			flatten = false
		case __sqlbundle_NoTerminate:
			terminate = false
		}
	}

	if flatten {
		out = __sqlbundle_flattenSQL(out)
	}
	if terminate {
		out += ";"
	}

	return dialect.Rebind(out)
}

func __sqlbundle_flattenSQL(x string) string {
	// trim whitespace from beginning and end
	s, e := 0, len(x)-1
	for s < len(x) && (x[s] == ' ' || x[s] == '\t' || x[s] == '\n') {
		s++
	}
	for s <= e && (x[e] == ' ' || x[e] == '\t' || x[e] == '\n') {
		e--
	}
	if s > e {
		return ""
	}
	x = x[s : e+1]

	// check for whitespace that needs fixing
	wasSpace := false
	for i := 0; i < len(x); i++ {
		r := x[i]
		justSpace := r == ' '
		if (wasSpace && justSpace) || r == '\t' || r == '\n' {
			// whitespace detected, start writing a new string
			var result strings.Builder
			result.Grow(len(x))
			if wasSpace {
				result.WriteString(x[:i-1])
			} else {
				result.WriteString(x[:i])
			}
			for p := i; p < len(x); p++ {
				for p < len(x) && (x[p] == ' ' || x[p] == '\t' || x[p] == '\n') {
					p++
				}
				result.WriteByte(' ')

				start := p
				for p < len(x) && !(x[p] == ' ' || x[p] == '\t' || x[p] == '\n') {
					p++
				}
				result.WriteString(x[start:p])
			}

			return result.String()
		}
		wasSpace = justSpace
	}

	// no problematic whitespace found
	return x
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_cockroach struct{}

func (p __sqlbundle_cockroach) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_pgx struct{}

func (p __sqlbundle_pgx) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_pgxcockroach struct{}

func (p __sqlbundle_pgxcockroach) Rebind(sql string) string {
	return __sqlbundle_postgres{}.Rebind(sql)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_postgres struct{}

func (p __sqlbundle_postgres) Rebind(sql string) string {
	type sqlParseState int
	const (
		sqlParseStart sqlParseState = iota
		sqlParseInStringLiteral
		sqlParseInQuotedIdentifier
		sqlParseInComment
	)

	out := make([]byte, 0, len(sql)+10)

	j := 1
	state := sqlParseStart
	for i := 0; i < len(sql); i++ {
		ch := sql[i]
		switch state {
		case sqlParseStart:
			switch ch {
			case '?':
				out = append(out, '$')
				out = append(out, strconv.Itoa(j)...)
				state = sqlParseStart
				j++
				continue
			case '-':
				if i+1 < len(sql) && sql[i+1] == '-' {
					state = sqlParseInComment
				}
			case '"':
				state = sqlParseInQuotedIdentifier
			case '\'':
				state = sqlParseInStringLiteral
			}
		case sqlParseInStringLiteral:
			if ch == '\'' {
				state = sqlParseStart
			}
		case sqlParseInQuotedIdentifier:
			if ch == '"' {
				state = sqlParseStart
			}
		case sqlParseInComment:
			if ch == '\n' {
				state = sqlParseStart
			}
		}
		out = append(out, ch)
	}

	return string(out)
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_spanner struct{}

func (p __sqlbundle_spanner) Rebind(sql string) string {
	return sql
}

// this type is specially named to match up with the name returned by the
// dialect impl in the sql package.
type __sqlbundle_sqlite3 struct{}

func (s __sqlbundle_sqlite3) Rebind(sql string) string {
	return sql
}

type __sqlbundle_Literal string

func (__sqlbundle_Literal) private() {}

func (l __sqlbundle_Literal) Render() string { return string(l) }

type __sqlbundle_Literals struct {
	Join string
	SQLs []__sqlbundle_SQL
}

func (__sqlbundle_Literals) private() {}

func (l __sqlbundle_Literals) Render() string {
	var out bytes.Buffer

	first := true
	for _, sql := range l.SQLs {
		if sql == nil {
			continue
		}
		if !first {
			out.WriteString(l.Join)
		}
		first = false
		out.WriteString(sql.Render())
	}

	return out.String()
}

type __sqlbundle_Condition struct {
	// set at compile/embed time
	Name  string
	Left  string
	Equal bool
	Right string

	// set at runtime
	Null bool
}

func (*__sqlbundle_Condition) private() {}

func (c *__sqlbundle_Condition) Render() string {
	// TODO(jeff): maybe check if we can use placeholders instead of the
	// literal null: this would make the templates easier.

	switch {
	case c.Equal && c.Null:
		return c.Left + " is null"
	case c.Equal && !c.Null:
		return c.Left + " = " + c.Right
	case !c.Equal && c.Null:
		return c.Left + " is not null"
	case !c.Equal && !c.Null:
		return c.Left + " != " + c.Right
	default:
		panic("unhandled case")
	}
}

type __sqlbundle_Hole struct {
	// set at compiile/embed time
	Name string

	// set at runtime or possibly embed time
	SQL __sqlbundle_SQL
}

func (*__sqlbundle_Hole) private() {}

func (h *__sqlbundle_Hole) Render() string {
	if h.SQL == nil {
		return ""
	}
	return h.SQL.Render()
}

//
// end runtime support for building sql statements
//

func (obj *pgxImpl) CreateNoReturn_Record(ctx context.Context,
	record_encryption_key_hash Record_EncryptionKeyHash_Field,
	record_created_at Record_CreatedAt_Field,
	record_public Record_Public_Field,
	record_satellite_address Record_SatelliteAddress_Field,
	record_macaroon_head Record_MacaroonHead_Field,
	record_encrypted_secret_key Record_EncryptedSecretKey_Field,
	record_encrypted_access_grant Record_EncryptedAccessGrant_Field,
	optional Record_Create_Fields) (
	err error) {
	__encryption_key_hash_val := record_encryption_key_hash.value()
	__created_at_val := record_created_at.value()
	__public_val := record_public.value()
	__public_project_id_val := optional.PublicProjectId.value()
	__satellite_address_val := record_satellite_address.value()
	__macaroon_head_val := record_macaroon_head.value()
	__expires_at_val := optional.ExpiresAt.value()
	__encrypted_secret_key_val := record_encrypted_secret_key.value()
	__encrypted_access_grant_val := record_encrypted_access_grant.value()
	__invalidation_reason_val := optional.InvalidationReason.value()
	__invalidated_at_val := optional.InvalidatedAt.value()
	__usage_tags_val := optional.UsageTags.value()
	__project_created_at_val := optional.ProjectCreatedAt.value()

	var __embed_stmt = __sqlbundle_Literal("INSERT INTO records ( encryption_key_hash, created_at, public, public_project_id, satellite_address, macaroon_head, expires_at, encrypted_secret_key, encrypted_access_grant, invalidation_reason, invalidated_at, usage_tags, project_created_at ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )")

	var __values []any
	__values = append(__values, __encryption_key_hash_val, __created_at_val, __public_val, __public_project_id_val, __satellite_address_val, __macaroon_head_val, __expires_at_val, __encrypted_secret_key_val, __encrypted_access_grant_val, __invalidation_reason_val, __invalidated_at_val, __usage_tags_val, __project_created_at_val)

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	_, err = obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return obj.makeErr(err)
	}
	return nil

}

func (obj *pgxImpl) Get_Record_By_EncryptionKeyHash(ctx context.Context,
	record_encryption_key_hash Record_EncryptionKeyHash_Field) (
	record *Record, err error) {

	var __embed_stmt = __sqlbundle_Literal("SELECT records.encryption_key_hash, records.created_at, records.public, records.public_project_id, records.satellite_address, records.macaroon_head, records.expires_at, records.encrypted_secret_key, records.encrypted_access_grant, records.invalidation_reason, records.invalidated_at, records.usage_tags, records.project_created_at FROM records WHERE records.encryption_key_hash = ?")

	var __values []any
	__values = append(__values, record_encryption_key_hash.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	record = &Record{}
	err = obj.queryRowContext(ctx, __stmt, __values...).Scan(&record.EncryptionKeyHash, &record.CreatedAt, &record.Public, &record.PublicProjectId, &record.SatelliteAddress, &record.MacaroonHead, &record.ExpiresAt, &record.EncryptedSecretKey, &record.EncryptedAccessGrant, &record.InvalidationReason, &record.InvalidatedAt, &record.UsageTags, &record.ProjectCreatedAt)
	if err != nil {
		return (*Record)(nil), obj.makeErr(err)
	}
	return record, nil

}

func (obj *pgxImpl) UpdateNoReturn_Record_By_EncryptionKeyHash_And_InvalidationReason_Is_Null(ctx context.Context,
	record_encryption_key_hash Record_EncryptionKeyHash_Field,
	update Record_Update_Fields) (
	err error) {

	var __sets = &__sqlbundle_Hole{}

	var __embed_stmt = __sqlbundle_Literals{Join: "", SQLs: []__sqlbundle_SQL{__sqlbundle_Literal("UPDATE records SET "), __sets, __sqlbundle_Literal(" WHERE records.encryption_key_hash = ? AND records.invalidation_reason is NULL")}}

	__sets_sql := __sqlbundle_Literals{Join: ", "}
	var __values []any
	var __args []any

	if update.InvalidationReason._set {
		__values = append(__values, update.InvalidationReason.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("invalidation_reason = ?"))
	}

	if update.InvalidatedAt._set {
		__values = append(__values, update.InvalidatedAt.value())
		__sets_sql.SQLs = append(__sets_sql.SQLs, __sqlbundle_Literal("invalidated_at = ?"))
	}

	if len(__sets_sql.SQLs) == 0 {
		return emptyUpdate()
	}

	__args = append(__args, record_encryption_key_hash.value())

	__values = append(__values, __args...)
	__sets.SQL = __sets_sql

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	_, err = obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return obj.makeErr(err)
	}
	return nil
}

func (obj *pgxImpl) Delete_Record_By_EncryptionKeyHash(ctx context.Context,
	record_encryption_key_hash Record_EncryptionKeyHash_Field) (
	deleted bool, err error) {

	var __embed_stmt = __sqlbundle_Literal("DELETE FROM records WHERE records.encryption_key_hash = ?")

	var __values []any
	__values = append(__values, record_encryption_key_hash.value())

	var __stmt = __sqlbundle_Render(obj.dialect, __embed_stmt)
	obj.logStmt(__stmt, __values...)

	__res, err := obj.driver.ExecContext(ctx, __stmt, __values...)
	if err != nil {
		return false, obj.makeErr(err)
	}

	__count, err := __res.RowsAffected()
	if err != nil {
		return false, obj.makeErr(err)
	}

	return __count > 0, nil

}

func (impl pgxImpl) isConstraintError(err error) (constraint string, ok bool) {
	if e, ok := err.(*pgconn.PgError); ok {
		if e.Code[:2] == "23" {
			return e.ConstraintName, true
		}
	}
	return "", false
}

func (obj *pgxImpl) deleteAll(ctx context.Context) (count int64, err error) {
	var __res sql.Result
	var __count int64
	__res, err = obj.driver.ExecContext(ctx, "DELETE FROM records;")
	if err != nil {
		return 0, obj.makeErr(err)
	}

	__count, err = __res.RowsAffected()
	if err != nil {
		return 0, obj.makeErr(err)
	}
	count += __count

	return count, nil

}

type Methods interface {
	CreateNoReturn_Record(ctx context.Context,
		record_encryption_key_hash Record_EncryptionKeyHash_Field,
		record_created_at Record_CreatedAt_Field,
		record_public Record_Public_Field,
		record_satellite_address Record_SatelliteAddress_Field,
		record_macaroon_head Record_MacaroonHead_Field,
		record_encrypted_secret_key Record_EncryptedSecretKey_Field,
		record_encrypted_access_grant Record_EncryptedAccessGrant_Field,
		optional Record_Create_Fields) (
		err error)

	Delete_Record_By_EncryptionKeyHash(ctx context.Context,
		record_encryption_key_hash Record_EncryptionKeyHash_Field) (
		deleted bool, err error)

	Get_Record_By_EncryptionKeyHash(ctx context.Context,
		record_encryption_key_hash Record_EncryptionKeyHash_Field) (
		record *Record, err error)

	UpdateNoReturn_Record_By_EncryptionKeyHash_And_InvalidationReason_Is_Null(ctx context.Context,
		record_encryption_key_hash Record_EncryptionKeyHash_Field,
		update Record_Update_Fields) (
		err error)
}

type TxMethods interface {
	Methods

	Rebind(s string) string
	Commit() error
	Rollback() error
}

type txMethods interface {
	TxMethods

	deleteAll(ctx context.Context) (int64, error)
	makeErr(err error) error
}

type DBMethods interface {
	Methods

	Schema() []string
	DropSchema() []string

	Rebind(sql string) string
}

type dbMethods interface {
	DBMethods

	wrapTx(tx *sql.Tx) txMethods
	makeErr(err error) error
}

func openpgx(source string) (*sql.DB, error) {
	return sql.Open("pgx", source)
}
