// Copyright (C) 2022 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: badgerauth_admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvalidateRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *InvalidateRecordRequest) Reset() {
	*x = InvalidateRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badgerauth_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRecordRequest) ProtoMessage() {}

func (x *InvalidateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRecordRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRecordRequest) Descriptor() ([]byte, []int) {
	return file_badgerauth_admin_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidateRecordRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InvalidateRecordRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InvalidateRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InvalidateRecordResponse) Reset() {
	*x = InvalidateRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badgerauth_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRecordResponse) ProtoMessage() {}

func (x *InvalidateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRecordResponse.ProtoReflect.Descriptor instead.
func (*InvalidateRecordResponse) Descriptor() ([]byte, []int) {
	return file_badgerauth_admin_proto_rawDescGZIP(), []int{1}
}

type UnpublishRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *UnpublishRecordRequest) Reset() {
	*x = UnpublishRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badgerauth_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpublishRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishRecordRequest) ProtoMessage() {}

func (x *UnpublishRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishRecordRequest.ProtoReflect.Descriptor instead.
func (*UnpublishRecordRequest) Descriptor() ([]byte, []int) {
	return file_badgerauth_admin_proto_rawDescGZIP(), []int{2}
}

func (x *UnpublishRecordRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type UnpublishRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnpublishRecordResponse) Reset() {
	*x = UnpublishRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badgerauth_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpublishRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishRecordResponse) ProtoMessage() {}

func (x *UnpublishRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishRecordResponse.ProtoReflect.Descriptor instead.
func (*UnpublishRecordResponse) Descriptor() ([]byte, []int) {
	return file_badgerauth_admin_proto_rawDescGZIP(), []int{3}
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badgerauth_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_badgerauth_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRecordRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badgerauth_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_badgerauth_admin_proto_rawDescGZIP(), []int{5}
}

var File_badgerauth_admin_proto protoreflect.FileDescriptor

var file_badgerauth_admin_proto_rawDesc = []byte{
	0x0a, 0x16, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72,
	0x61, 0x75, 0x74, 0x68, 0x1a, 0x10, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x17, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x16, 0x55, 0x6e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x9c, 0x02, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5d, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x23, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5a, 0x0a, 0x0f, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x22, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x62, 0x61,
	0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62,
	0x61, 0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c,
	0x5a, 0x2a, 0x73, 0x74, 0x6f, 0x72, 0x6a, 0x2e, 0x69, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2d, 0x6d, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x62,
	0x61, 0x64, 0x67, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_badgerauth_admin_proto_rawDescOnce sync.Once
	file_badgerauth_admin_proto_rawDescData = file_badgerauth_admin_proto_rawDesc
)

func file_badgerauth_admin_proto_rawDescGZIP() []byte {
	file_badgerauth_admin_proto_rawDescOnce.Do(func() {
		file_badgerauth_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_badgerauth_admin_proto_rawDescData)
	})
	return file_badgerauth_admin_proto_rawDescData
}

var file_badgerauth_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_badgerauth_admin_proto_goTypes = []interface{}{
	(*InvalidateRecordRequest)(nil),  // 0: badgerauth.InvalidateRecordRequest
	(*InvalidateRecordResponse)(nil), // 1: badgerauth.InvalidateRecordResponse
	(*UnpublishRecordRequest)(nil),   // 2: badgerauth.UnpublishRecordRequest
	(*UnpublishRecordResponse)(nil),  // 3: badgerauth.UnpublishRecordResponse
	(*DeleteRecordRequest)(nil),      // 4: badgerauth.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),     // 5: badgerauth.DeleteRecordResponse
}
var file_badgerauth_admin_proto_depIdxs = []int32{
	0, // 0: badgerauth.AdminService.InvalidateRecord:input_type -> badgerauth.InvalidateRecordRequest
	2, // 1: badgerauth.AdminService.UnpublishRecord:input_type -> badgerauth.UnpublishRecordRequest
	4, // 2: badgerauth.AdminService.DeleteRecord:input_type -> badgerauth.DeleteRecordRequest
	1, // 3: badgerauth.AdminService.InvalidateRecord:output_type -> badgerauth.InvalidateRecordResponse
	3, // 4: badgerauth.AdminService.UnpublishRecord:output_type -> badgerauth.UnpublishRecordResponse
	5, // 5: badgerauth.AdminService.DeleteRecord:output_type -> badgerauth.DeleteRecordResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_badgerauth_admin_proto_init() }
func file_badgerauth_admin_proto_init() {
	if File_badgerauth_admin_proto != nil {
		return
	}
	file_badgerauth_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_badgerauth_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidateRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badgerauth_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidateRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badgerauth_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpublishRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badgerauth_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpublishRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badgerauth_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badgerauth_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_badgerauth_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badgerauth_admin_proto_goTypes,
		DependencyIndexes: file_badgerauth_admin_proto_depIdxs,
		MessageInfos:      file_badgerauth_admin_proto_msgTypes,
	}.Build()
	File_badgerauth_admin_proto = out.File
	file_badgerauth_admin_proto_rawDesc = nil
	file_badgerauth_admin_proto_goTypes = nil
	file_badgerauth_admin_proto_depIdxs = nil
}
