// Copyright (C) 2021 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: badgerauth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record_State int32

const (
	Record_CREATED Record_State = 0
)

// Enum value maps for Record_State.
var (
	Record_State_name = map[int32]string{
		0: "CREATED",
	}
	Record_State_value = map[string]int32{
		"CREATED": 0,
	}
)

func (x Record_State) Enum() *Record_State {
	p := new(Record_State)
	*p = x
	return p
}

func (x Record_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Record_State) Descriptor() protoreflect.EnumDescriptor {
	return file_badgerauth_proto_enumTypes[0].Descriptor()
}

func (Record_State) Type() protoreflect.EnumType {
	return &file_badgerauth_proto_enumTypes[0]
}

func (x Record_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Record_State.Descriptor instead.
func (Record_State) EnumDescriptor() ([]byte, []int) {
	return file_badgerauth_proto_rawDescGZIP(), []int{0, 0}
}

type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// record data
	CreatedAtUnix int64    `protobuf:"varint,1,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Public        bool     `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	UsageTags     []string `protobuf:"bytes,12,rep,name=usage_tags,json=usageTags,proto3" json:"usage_tags,omitempty"`
	// denormalized information from access grant
	SatelliteAddress     string `protobuf:"bytes,3,opt,name=satellite_address,json=satelliteAddress,proto3" json:"satellite_address,omitempty"`
	PublicProjectId      []byte `protobuf:"bytes,11,opt,name=public_project_id,json=publicProjectId,proto3" json:"public_project_id,omitempty"`
	MacaroonHead         []byte `protobuf:"bytes,4,opt,name=macaroon_head,json=macaroonHead,proto3" json:"macaroon_head,omitempty"`
	ExpiresAtUnix        int64  `protobuf:"varint,5,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	ProjectCreatedAtUnix int64  `protobuf:"varint,13,opt,name=project_created_at_unix,json=projectCreatedAtUnix,proto3" json:"project_created_at_unix,omitempty"`
	// sensitive data
	EncryptedSecretKey   []byte `protobuf:"bytes,6,opt,name=encrypted_secret_key,json=encryptedSecretKey,proto3" json:"encrypted_secret_key,omitempty"`
	EncryptedAccessGrant []byte `protobuf:"bytes,7,opt,name=encrypted_access_grant,json=encryptedAccessGrant,proto3" json:"encrypted_access_grant,omitempty"`
	// invalidation tracking
	InvalidationReason string `protobuf:"bytes,8,opt,name=invalidation_reason,json=invalidationReason,proto3" json:"invalidation_reason,omitempty"`
	InvalidatedAtUnix  int64  `protobuf:"varint,9,opt,name=invalidated_at_unix,json=invalidatedAtUnix,proto3" json:"invalidated_at_unix,omitempty"`
	// deprecated synchronization-related data
	State         Record_State `protobuf:"varint,10,opt,name=state,proto3,enum=badgerauth.Record_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_badgerauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_badgerauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_badgerauth_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Record) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Record) GetUsageTags() []string {
	if x != nil {
		return x.UsageTags
	}
	return nil
}

func (x *Record) GetSatelliteAddress() string {
	if x != nil {
		return x.SatelliteAddress
	}
	return ""
}

func (x *Record) GetPublicProjectId() []byte {
	if x != nil {
		return x.PublicProjectId
	}
	return nil
}

func (x *Record) GetMacaroonHead() []byte {
	if x != nil {
		return x.MacaroonHead
	}
	return nil
}

func (x *Record) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Record) GetProjectCreatedAtUnix() int64 {
	if x != nil {
		return x.ProjectCreatedAtUnix
	}
	return 0
}

func (x *Record) GetEncryptedSecretKey() []byte {
	if x != nil {
		return x.EncryptedSecretKey
	}
	return nil
}

func (x *Record) GetEncryptedAccessGrant() []byte {
	if x != nil {
		return x.EncryptedAccessGrant
	}
	return nil
}

func (x *Record) GetInvalidationReason() string {
	if x != nil {
		return x.InvalidationReason
	}
	return ""
}

func (x *Record) GetInvalidatedAtUnix() int64 {
	if x != nil {
		return x.InvalidatedAtUnix
	}
	return 0
}

func (x *Record) GetState() Record_State {
	if x != nil {
		return x.State
	}
	return Record_CREATED
}

var File_badgerauth_proto protoreflect.FileDescriptor

const file_badgerauth_proto_rawDesc = "" +
	"\n" +
	"\x10badgerauth.proto\x12\n" +
	"badgerauth\"\xd3\x04\n" +
	"\x06Record\x12&\n" +
	"\x0fcreated_at_unix\x18\x01 \x01(\x03R\rcreatedAtUnix\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public\x12\x1d\n" +
	"\n" +
	"usage_tags\x18\f \x03(\tR\tusageTags\x12+\n" +
	"\x11satellite_address\x18\x03 \x01(\tR\x10satelliteAddress\x12*\n" +
	"\x11public_project_id\x18\v \x01(\fR\x0fpublicProjectId\x12#\n" +
	"\rmacaroon_head\x18\x04 \x01(\fR\fmacaroonHead\x12&\n" +
	"\x0fexpires_at_unix\x18\x05 \x01(\x03R\rexpiresAtUnix\x125\n" +
	"\x17project_created_at_unix\x18\r \x01(\x03R\x14projectCreatedAtUnix\x120\n" +
	"\x14encrypted_secret_key\x18\x06 \x01(\fR\x12encryptedSecretKey\x124\n" +
	"\x16encrypted_access_grant\x18\a \x01(\fR\x14encryptedAccessGrant\x12/\n" +
	"\x13invalidation_reason\x18\b \x01(\tR\x12invalidationReason\x12.\n" +
	"\x13invalidated_at_unix\x18\t \x01(\x03R\x11invalidatedAtUnix\x12.\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2\x18.badgerauth.Record.StateR\x05state\"\x14\n" +
	"\x05State\x12\v\n" +
	"\aCREATED\x10\x00B&Z$storj.io/edge/pkg/auth/badgerauth/pbb\x06proto3"

var (
	file_badgerauth_proto_rawDescOnce sync.Once
	file_badgerauth_proto_rawDescData []byte
)

func file_badgerauth_proto_rawDescGZIP() []byte {
	file_badgerauth_proto_rawDescOnce.Do(func() {
		file_badgerauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badgerauth_proto_rawDesc), len(file_badgerauth_proto_rawDesc)))
	})
	return file_badgerauth_proto_rawDescData
}

var file_badgerauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_badgerauth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_badgerauth_proto_goTypes = []any{
	(Record_State)(0), // 0: badgerauth.Record.State
	(*Record)(nil),    // 1: badgerauth.Record
}
var file_badgerauth_proto_depIdxs = []int32{
	0, // 0: badgerauth.Record.state:type_name -> badgerauth.Record.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_badgerauth_proto_init() }
func file_badgerauth_proto_init() {
	if File_badgerauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badgerauth_proto_rawDesc), len(file_badgerauth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_badgerauth_proto_goTypes,
		DependencyIndexes: file_badgerauth_proto_depIdxs,
		EnumInfos:         file_badgerauth_proto_enumTypes,
		MessageInfos:      file_badgerauth_proto_msgTypes,
	}.Build()
	File_badgerauth_proto = out.File
	file_badgerauth_proto_goTypes = nil
	file_badgerauth_proto_depIdxs = nil
}
