{
 "title": "DC: overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "datacenter",
    "query": {
     "query": "label_values(datacenter_location)"
    }
   },
   {
    "name": "i",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{datacenter_location=~\"$dc\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$dc/$i network utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))"
    }
   ]
  },
  {
   "title": "TX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))"
    }
   ]
  },
  {
   "title": "RX (packets)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))"
    }
   ]
  },
  {
   "title": "TX (packets)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_packets_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))"
    }
   ]
  },
  {
   "title": "TCP sockets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_sockstat_TCP_alloc{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "Change in number of TCP sockets in last 5 minutes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(node_sockstat_TCP_alloc{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))"
    }
   ]
  },
  {
   "title": "TCP memory size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_sockstat_TCP_mem_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "Change in TCP memory size in last 5 minutes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(node_sockstat_TCP_mem_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))"
    }
   ]
  },
  { "title": "$dc/$i CPU utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Load (1 min average / cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1{datacenter_location=~\"$dc\", instance=~\"$i\"}) / count(node_cpu_seconds_total{mode=\"idle\", datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "Load (5 min average / cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load5{datacenter_location=~\"$dc\", instance=~\"$i\"}) / count(node_cpu_seconds_total{mode=\"idle\", datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "Load (15 min average / cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load15{datacenter_location=~\"$dc\", instance=~\"$i\"}) / count(node_cpu_seconds_total{mode=\"idle\", datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  { "title": "CPU utilization alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Load (1 min average / cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_load1) by (datacenter_location, instance) / count(node_cpu_seconds_total{mode=\"idle\"}) by (datacenter_location, instance)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  { "title": "$dc/$i RAM utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "% of RAM used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"} * 100) / node_memory_MemTotal_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"}) - sum(node_memory_MemFree_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "% of RAM used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemFree_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"}) / sum(node_memory_MemTotal_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  { "title": "RAM utilization alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "% of RAM used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "prediction of % of RAM used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp(100 - ((predict_linear(node_memory_MemAvailable_bytes[2h], 24 * 3600) * 100) / node_memory_MemTotal_bytes), 0, 100)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  { "title": "$dc/$i disk utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Read",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Write",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m])",
     "legendFormat": "Read/{{datacenter_location}}/{{instance}}/{{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{datacenter_location=~\"$dc\", instance=~\"$i\"}[5m])",
     "legendFormat": "Write/{{datacenter_location}}/{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "Used space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"}) - sum(node_filesystem_avail_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  {
   "title": "% of space used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_avail_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"}) / sum(node_filesystem_size_bytes{datacenter_location=~\"$dc\", instance=~\"$i\"})"
    }
   ]
  },
  { "title": "Disk utilization alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "% of used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_avail_bytes) by (datacenter_location,instance) / sum(node_filesystem_size_bytes) by (datacenter_location,instance)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "prediction of % of used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp(1 - sum(predict_linear(node_filesystem_avail_bytes[5m], 24 * 3600)) by (datacenter_location,instance) / sum(node_filesystem_size_bytes) by (datacenter_location,instance), 0, 1)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  }
 ]
}