{
 "title": "Gateway-MT: unmapped errors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "datacenter",
    "query": {
     "query": "label_values(datacenter_location)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(gmt_unmapped_error{datacenter_location=~\"$dc\"}, instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(gmt_unmapped_error{instance=~\"$instance\"}, api)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sum of error rates by error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gmt_unmapped_error{field=\"total\"}[5m])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Sum of errors by error",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gmt_unmapped_error{field=\"total\"}) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "$endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "endpoint" },
  {
   "title": "rate of errors @ $endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(gmt_unmapped_error{api=~\"$endpoint\",datacenter_location=~\"$dc\",field=\"total\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{error}} ({{datacenter_location}}/{{instance}})"
    }
   ]
  },
  {
   "title": "error count @ $endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gmt_unmapped_error{api=~\"$endpoint\",datacenter_location=~\"$dc\",field=\"total\",instance=~\"$instance\"}",
     "legendFormat": "{{error}} ({{datacenter_location}}/{{instance}})"
    }
   ]
  }
 ]
}