{
 "title": "Gateway-MT: request times",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "datacenter",
    "query": {
     "query": "label_values(datacenter_location)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(gmt_request_times{datacenter_location=~\"$dc\"}, instance)"
    }
   },
   {
    "name": "code",
    "label": "code",
    "query": {
     "query": "label_values(gmt_request_times{instance=~\"$instance\"}, status_code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate to $dc/$instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gmt_request_times{datacenter_location=~\"$dc\",field=\"count\",instance=~\"$instance\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "% of traffic rate with non-2xx response ($dc/$instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gmt_request_times{datacenter_location=~\"$dc\",field=\"count\",instance=~\"$instance\",status_code!~\"_2.*\"}[5m])) / sum(rate(gmt_request_times{datacenter_location=~\"$dc\",field=\"count\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "% of traffic"
    }
   ]
  },
  {
   "title": "Average response time of $dc/$instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(gmt_request_times{datacenter_location=~\"$dc\",instance=~\"$instance\",field=\"sum\"}[5m])) by (status_code) / sum(rate(gmt_request_times{datacenter_location=~\"$dc\",instance=~\"$instance\",field=\"count\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Increase of requests in last 5 minutes ($dc/$instance)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gmt_request_times{datacenter_location=~\"$dc\",field=\"count\",instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Increase of 2xx responses in last 5 minutes ($dc/$instance)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gmt_request_times{datacenter_location=~\"$dc\",field=\"count\",instance=~\"$instance\",status_code=~\"_2.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Increase of non-2xx responses in last 5 minutes ($dc/$instance)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gmt_request_times{datacenter_location=~\"$dc\",field=\"count\",instance=~\"$instance\",status_code!~\"_2.*\"}[5m]))"
    }
   ]
  },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "% of traffic rate with a non-2xx response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gmt_request_times{field=\"count\",status_code!~\"_2.*\"}[5m])) by (datacenter_location, instance) / sum(rate(gmt_request_times{field=\"count\"}[5m])) by (datacenter_location, instance)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(gmt_request_times{field=\"sum\"}[5m]) / ignoring (field) rate(gmt_request_times{field=\"count\"}[5m])",
     "legendFormat": "{{datacenter_location}}/{{instance}}/{{status_code}}"
    }
   ]
  }
 ]
}