{
 "title": "Services: overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "dc",
    "query": {
     "query": "label_values(datacenter_location)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{datacenter_location=~\"$dc\"}, instance)"
    }
   },
   {
    "name": "appname",
    "label": "appname",
    "query": {
     "query": "label_values(up{instance=~\"$instance\"}, appname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open connections by entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "traefik_entrypoint_open_connections{datacenter_location=~\"$dc\", instance=~\"$instance\"}",
     "legendFormat": "{{datacenter_location}}/{{instance}}/{{environment_name}}/{{entrypoint}}/{{method}}"
    }
   ]
  },
  {
   "title": "Open connections by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "traefik_service_open_connections{datacenter_location=~\"$dc\", instance=~\"$instance\"}",
     "legendFormat": "{{datacenter_location}}/{{instance}}/{{environment_name}}/{{service}}/{{method}}"
    }
   ]
  },
  { "title": "$dc/$instance/$appname service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "rate of uplink_net_error_needed_retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(uplink_net_error_needed_retry{datacenter_location=~\"$dc\", instance=~\"$instance\", appname=~\"$appname\", field=\"total\"}[5m])",
     "legendFormat": "{{datacenter_location}}/{{instance}}/{{appname}}/{{scope}}"
    }
   ]
  },
  {
   "title": "rate of uplink_net_error_needed_retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(download_stripe_failed_not_enough_pieces_uplink{datacenter_location=~\"$dc\", instance=~\"$instance\", appname=~\"$appname\", field=\"total\"}[5m])",
     "legendFormat": "{{datacenter_location}}/{{instance}}/{{appname}}/{{scope}}"
    }
   ]
  }
 ]
}