{
 "title": "#team-edge's alerting dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Alerts from this dashboard", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Load (1 min average / cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_load1) by (datacenter_location, instance) / count(node_cpu_seconds_total{mode=\"idle\"}) by (datacenter_location, instance)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "RAM (currently no alerts for % of RAM used)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "% of RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "prediction of % of RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp(100 - ((predict_linear(node_memory_MemAvailable_bytes[2h], 24 * 3600) * 100) / node_memory_MemTotal_bytes), 0, 100)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "% of used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_avail_bytes) by (datacenter_location,instance) / sum(node_filesystem_size_bytes) by (datacenter_location,instance)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "prediction of % of used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp(1 - sum(predict_linear(node_filesystem_avail_bytes[5m], 24 * 3600)) by (datacenter_location,instance) / sum(node_filesystem_size_bytes) by (datacenter_location,instance), 0, 1)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  },
  {
   "title": "GMT (currently no alerts for Average response time)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(gmt_request_times{field=\"sum\"}[5m]) / ignoring (field) rate(gmt_request_times{field=\"count\"}[5m])",
     "legendFormat": "{{datacenter_location}}/{{instance}}/{{status_code}}"
    }
   ]
  },
  {
   "title": "% of traffic rate with a non-2xx response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gmt_request_times{field=\"count\",status_code!~\"_2.*\"}[5m])) by (datacenter_location, instance) / sum(rate(gmt_request_times{field=\"count\"}[5m])) by (datacenter_location, instance)",
     "legendFormat": "{{datacenter_location}}/{{instance}}"
    }
   ]
  }
 ]
}