version: "3.8"

volumes:
  storjsimconfig:
  localgopath:

services:
  redis:
    image: redis:6.0.9
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=dcstorj
  storjsim:
    image: golang:1.17.7
    entrypoint: /scripts/start-storj-sim.sh
    volumes:
      - localgopath:/go/storjpath
      - ${STORJ_SRC_DIR}:/code
      - ./start-storj-sim.sh:/scripts/start-storj-sim.sh
      - storjsimconfig:/root/.local/share/storj
    ports:
      - "10000:10000"
      - "10001:10001"
    env_file:
      - service.env
    depends_on:
      - postgres
      - redis
  authservice:
    image: golang:1.17.7
    entrypoint: /scripts/start-auth-service.sh
    volumes:
      - localgopath:/go/storjpath
      - ${GATEWAY_SRC_DIR}:/code
      - ./start-auth-service.sh:/scripts/start-auth-service.sh
      - storjsimconfig:/config
    ports:
      - "20000:20000"
    depends_on:
      - storjsim
    env_file:
      - service.env
  gateway-mt:
    image: golang:1.17.7
    volumes:
      - localgopath:/go/storjpath
      - ${GATEWAY_SRC_DIR}:/code
      - ./start-gateway-mt.sh:/scripts/start-gateway-mt.sh
      - storjsimconfig:/config
    env_file:
      - service.env
    ports:
      - "20010:20010"
      - "20019:20019"
    entrypoint: /scripts/start-gateway-mt.sh
    depends_on:
      - storjsim
      - authservice
      - tracing
  linksharing:
    image: golang:1.17.7
    entrypoint: /scripts/start-linksharing.sh
    volumes:
      - localgopath:/go/storjpath
      - ${GATEWAY_SRC_DIR}:/code
      - ./start-linksharing.sh:/scripts/start-linksharing.sh
    ports:
      - "20020:20020"
    depends_on:
      - authservice
      - storjsim
  tracing:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # this is the web UI
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
